/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.pad;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int content_body=0x7f06000e;
        public static final int content_title=0x7f06000d;
        public static final int create=0x7f060005;
        public static final int createnew=0x7f060004;
        public static final int editbody=0x7f060006;
        public static final int emptyText=0x7f06000c;
        public static final int icon=0x7f060009;
        public static final int listpage=0x7f060002;
        public static final int listrow1=0x7f060007;
        public static final int listrow2=0x7f060008;
        public static final int listrowDescription=0x7f06000b;
        public static final int listrowTitle=0x7f06000a;
        public static final int menu_append=0x7f060010;
        public static final int menu_confirm=0x7f06000f;
        public static final int menu_down=0x7f060013;
        public static final int menu_top=0x7f060011;
        public static final int menu_up=0x7f060012;
        public static final int optionlist=0x7f060003;
        public static final int pagewrap=0x7f060000;
        public static final int viewpage=0x7f060001;
    }
    public static final class layout {
        public static final int list=0x7f030000;
        public static final int listrow=0x7f030001;
        public static final int listrowdetail=0x7f030002;
        public static final int listscroller=0x7f030003;
        public static final int viewer=0x7f030004;
    }
    public static final class string {
        public static final int about_title=0x7f040003;
        public static final int app_name=0x7f040000;
        public static final int content_body=0x7f040006;
        public static final int content_path=0x7f040004;
        public static final int content_saved=0x7f040007;
        public static final int content_title=0x7f040005;
        public static final int menu_add=0x7f04000b;
        public static final int menu_append=0x7f04000a;
        public static final int menu_configure=0x7f04000d;
        public static final int menu_confirm=0x7f040009;
        public static final int menu_delete=0x7f04000e;
        public static final int menu_down=0x7f040010;
        public static final int menu_edit=0x7f040008;
        public static final int menu_list=0x7f040012;
        public static final int menu_share=0x7f04000c;
        public static final int menu_top=0x7f04000f;
        public static final int menu_up=0x7f040011;
        public static final int pssstrsa=0x7f040002;
        public static final int welcome=0x7f040001;
    }
    public static final class style {
        public static final int Theme_NoBackground=0x7f050000;
        public static final int Theme_Pad=0x7f050001;
    }
}
